---
title: "Figure 1"
output:
  pdf_document:
    fig_caption: yes
---

```{r setup_01, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
```

# Figure 1

```{r read_chunks_01, cache=FALSE, echo=TRUE}
knitr::read_chunk("../scripts/99_utils.R")
```

```{r source_utils, message=FALSE, results='hide', echo=FALSE, warning=FALSE}

```

```{r 01_size-comparison, echo=TRUE, warning=FALSE, fig.width = 5.2, fig.height = 2.2, message=FALSE}
# ---- size_comparison ----
# setwd("scripts"); source("../scripts/99_utils.R")
gpkg_path <- "../data/gis.gpkg"
states   <- st_read(gpkg_path, layer = "states", stringsAsFactors = FALSE, quiet = TRUE)
hu4s     <- st_read(gpkg_path, layer = "hu4s", stringsAsFactors = FALSE, quiet = TRUE)
hu8s     <- st_read(gpkg_path, layer = "hu8s", stringsAsFactors = FALSE, quiet = TRUE)
counties <- st_read(gpkg_path, layer = "counties", stringsAsFactors = FALSE, quiet = TRUE)
iws      <- st_read(gpkg_path, layer = "iws", stringsAsFactors = FALSE, quiet = TRUE)

q          <- seq(0, 1, length.out = 20)
res        <- lapply(list(hu4s, counties, iws, hu8s),
              function(x) as.numeric(quantile(st_area(x), probs = q)))
names(res) <- c("hu4", "county", "iws", "hu8s")
res        <- dplyr::bind_rows(res) %>%
  mutate(q = q) %>%
  tidyr::gather(key = "scale", value = "area", -q) %>%
  mutate(scale = factor(scale, levels = c("iws", "county", "hu8s", "hu4")))

theme_opts <- theme_minimal() +
  theme(axis.title = element_text(size = 12),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 8), 
        axis.line = element_line(), 
        plot.margin = unit(c(0, -0.13, 0, -0.13), "cm"))

color_key <- setNames(viridis::viridis(4), 
                      c("iws", "county", "hu8s", "hu4"))

g_full <- ggplot() +
  geom_line(data = res, aes(x = area, y = rev(q), color = scale), size = 1.1) +
  ylab("Density") + xlab(bquote('Area ('*m^2~')')) +
  scale_x_continuous(labels = c("2^10", "10^10", "11^10", "12^10"),
                     breaks = c(10^2, 10^10, 11^10, 12^10)) +
  scale_color_manual(values = color_key) +
  theme_opts +
  labs(color = "")

g_zoom <- ggplot() +
  geom_line(data = dplyr::filter(res, scale %in% c("iws", "county", "hu8s")), 
            aes(x = area, y = rev(q), color = scale), size = 1.1) +
  ylab("Density") + xlab(bquote('Area ('*m^2~')')) +
  scale_x_continuous(labels = c("2^10", "10^10"),
                     breaks = c(2^10, 10^10)) + 
  scale_color_manual(values = color_key) +
  theme_opts +
  labs(color = "")

legend <- get_legend(g_full)

plot_grid(
  g_zoom + theme(legend.position = "none"),
  g_full + theme(legend.position = "none", 
                 axis.text.y = element_blank()) +
    ylab(""), 
  plot_grid(NULL, legend, NULL, ncol = 1, rel_heights = c(0.2, 1, 0.4)) + 
    theme(legend.box.margin = unit(c(0, -0.4, 0, -0.13), "cm")),
  nrow = 1, rel_widths = c(1, 1, 0.6), align = "v", 
  labels = c("A.", "B.", ""), hjust = c(-9.7, -9.8, 0))
```
