---
title: "Figures"
output:
  pdf_document:
    fig_caption: yes
---

```{r setup_03, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
```

```{r read_chunks_03, cache=FALSE, echo=FALSE}
# setwd("scripts"); source("../scripts/99_utils.R")
knitr::read_chunk("../scripts/99_utils.R")
```

```{r source_utils, message=FALSE, results='hide', echo=FALSE, warning=FALSE}

```

```{r 03_scatter_plot, echo=FALSE, warning=FALSE, fig.width = 5.5, fig.height = 2.7}
ep_fake <- readRDS("../data/ep_fake.rds")

# cowplot of tp vs notill
plot_grid(
  # county
ggplot() + 
  geom_point(data = ep_fake, aes(x = pctnotil_county, y = ep_fake), 
             size = 0.3) +
  ylab("y") + xlab("tillage percent"),
# hu8
ggplot() + 
  geom_point(data = ep_fake, aes(x = pctnotil_hu8, y = ep_fake), 
             size = 0.3) + 
  theme(axis.text.y = element_blank(), 
        axis.title.y = element_blank()) +
  ylab("y") + xlab("tillage percent"),
# hu4
ggplot() + 
  geom_point(data = ep_fake, aes(x = pctnotil_hu4, y = ep_fake), 
             size = 0.3) + 
  theme(axis.text.y = element_blank(), 
        axis.title.y = element_blank()) +
  ylab("y") + xlab("tillage percent"),
nrow = 1, rel_widths = c(1, 0.75, 0.75))
```

```{r ep_real_vs_pctnotil, echo=FALSE, warning=FALSE, fig.width = 5.5, fig.height = 3, eval=FALSE}
gpkg_path <- "../data/gis.gpkg"
hu4s             <- st_read(gpkg_path, layer = "hu4s", stringsAsFactors = FALSE)
hu4_tillage      <- readRDS("../data/hu4_tillage.rds")
hu8s             <- st_read(gpkg_path, layer = "hu8s", stringsAsFactors = FALSE)
hu8_tillage      <- readRDS("../data/hu8_tillage.rds")
states           <- st_read(gpkg_path, layer = "states", stringsAsFactors = FALSE)
counties         <- st_read(gpkg_path, layer = "counties", 
                            stringsAsFactors = FALSE)
counties_tillage <- readRDS("../data/counties_tillage.rds")
lg               <- lagosne_load()
ep_raw           <- readRDS("../data/ep_nutr.rds")

# join huc ids
ep <- ep_raw %>%
  left_join(dplyr::select(lg$locus, lagoslakeid, 
                          hu4_zoneid, hu8_zoneid, 
                          county_zoneid, state_zoneid)) %>%
  left_join(dplyr::select(st_drop_geometry(hu4_tillage), ZoneID, pctnotil), 
                          by = c("hu4_zoneid" = "ZoneID")) %>% 
  drop_na(pctnotil) %>%
  rename(pctnotil_hu4 = pctnotil) %>%
  left_join(dplyr::select(st_drop_geometry(hu8_tillage), ZoneID, pctnotil), 
                          by = c("hu8_zoneid" = "ZoneID")) %>%
  rename(pctnotil_hu8 = pctnotil) %>% 
  
  left_join(dplyr::select(st_drop_geometry(counties_tillage), county_zoneid, pctnotil), 
                          by = c("county_zoneid")) %>%
  rename(pctnotil_county = pctnotil)

# cowplot of tp vs notill
plot_grid(
  ggplot() + 
    geom_point(data = ep, aes(x = pctnotil_county, y = tn)),
  ggplot() + 
    geom_point(data = ep, aes(x = pctnotil_hu8, y = tn)),
  ggplot() + 
    geom_point(data = ep, aes(x = pctnotil_hu4, y = tn))
)

```
