---
title: "Figure 4"
output:
  pdf_document:
    fig_caption: yes
---

```{r setup_04, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
```

# Figure 4

```{r read_chunks_04, cache=FALSE, echo=FALSE}
# setwd("scripts"); source("../scripts/99_utils.R")
knitr::read_chunk("../scripts/99_utils.R")
```

```{r source_utils, message=FALSE, results='hide', echo=FALSE, warning=FALSE}

```

```{r 04_variograms, echo=TRUE, warning=FALSE, fig.width = 5.5, fig.height = 3}
ep_fake <- readRDS("../data/ep_fake.rds")

hu8 <- ep_fake %>%
    dplyr::select(ep_fake, contains("hu8")) %>%
    dplyr::filter(!duplicated(hu8_zoneid)) %>%
    coordinatize(latname = "hu8_lat", longname = "hu8_long") %>%
    st_transform(crs = LAGOSNEgis:::albers_conic())

hu4 <- ep_fake %>%
    dplyr::select(ep_fake, contains("hu4")) %>%
    dplyr::filter(!duplicated(hu4_zoneid)) %>%
    coordinatize(latname = "hu4_lat", longname = "hu4_long") %>%
    st_transform(crs = LAGOSNEgis:::albers_conic())

county <- ep_fake %>%
    dplyr::select(ep_fake, contains("county"), contains("conty")) %>%
    dplyr::filter(!duplicated(county_zoneid)) %>%
    coordinatize(latname = "county_lat", longname = "conty_long") %>%
    st_transform(crs = LAGOSNEgis:::albers_conic())

make_variograms <- function(dt){
  var1    <- variogram(
    as.formula(paste0(names(dt)[grep("pctnotil", names(dt))], 
                      "~ coords.x1 + coords.x2")), 
                      data = as_Spatial(dt))
  v.fit1  <- fit.variogram(var1, vgm(psill = 50, model = "Exp", 
                                    range = 500000, nugget = 50))
  
  preds1  <- variogramLine(v.fit1, maxdist = max(var1$dist))
  preds1  <- mutate(preds1, id = "pctnotil") 
  var1    <- mutate(var1, id = "pctnotil")
  
  var2    <- variogram(ep_fake ~ coords.x1 + coords.x2, 
                      data = as_Spatial(dt))
  v.fit2  <- fit.variogram(var2, vgm(psill = 50, model = "Exp", 
                                    range = 500000, nugget = 50))
  preds2  <- variogramLine(v.fit2, maxdist = max(var2$dist))  
  var2    <- mutate(var2, id = "y")
  preds2  <- mutate(preds2, id = "y")
  
  suppressWarnings(
    var   <- dplyr::bind_rows(var1, var2))
  suppressWarnings(
    preds <- dplyr::bind_rows(preds1, preds2))
  
  tidy_variogram <- function(vfit, id){
      mutate(vfit, 
             model_name = !!(id), 
             sill = sum(psill, na.rm = TRUE),
             nugget = psill[model == "Nug"]) %>%
        filter(model != "Nug") %>%
        dplyr::select(model_name, model, range, sill, nugget)
  }
  
  fit_stats <- dplyr::bind_rows(
    tidy_variogram(v.fit1, id = "pctnotil"),
    tidy_variogram(v.fit2, id = "y"))
  
  list(var = var, preds = preds, fit_stats = fit_stats)
}  

hu8_v    <- make_variograms(hu8)
hu8_v$fit_stats
hu4_v    <- make_variograms(hu4)
hu4_v$fit_stats
county_v <- make_variograms(county)
county_v$fit_stats

theme_opts <- theme(axis.text.x = element_text(angle = 90), 
                    legend.position = "none", 
                    plot.title = element_text(hjust = 0.1))

legend <- get_legend(
  ggplot() +
  geom_point(data = county_v$var, aes(x = dist, y = gamma, color = id)) + 
    theme(legend.direction = "horizontal", 
        legend.title = element_blank()) +
  scale_color_viridis_d(labels = c("tillage percent", "y"))
  )

(g <- plot_grid(
ggplot() +
  geom_point(data = county_v$var, aes(x = dist, y = gamma, color = id)) +
  geom_line(data = county_v$preds, aes(x = dist, y = gamma, color = id)) + 
  scale_color_viridis_d(labels = c("tillage percent", "y")) +
  ggtitle("a. County") +
  theme_opts, 
ggplot() +
  geom_point(data = hu8_v$var, aes(x = dist, y = gamma, color = id)) +
  geom_line(data = hu8_v$preds, aes(x = dist, y = gamma, color = id)) + 
  scale_color_viridis_d(labels = c("tillage percent", "y")) +
  # geom_hline(aes(yintercept = 162.9 + 107)) +
  ggtitle("b. Subbasin") +  
  theme_opts + theme(axis.text.y = element_blank(), 
                     axis.title.y = element_blank()),
ggplot() +
  geom_point(data = hu4_v$var, aes(x = dist, y = gamma, color = id)) +
  geom_line(data = hu4_v$preds, aes(x = dist, y = gamma, color = id)) + 
  scale_color_viridis_d(labels = c("tillage percent", "y")) +
  ggtitle("c. Subregion") + 
  theme_opts + theme(axis.text.y = element_blank(), 
                     axis.title.y = element_blank()),
nrow = 1, rel_widths = c(1, 0.75, 0.75)))

plot_grid(g,
          plot_grid(NULL, legend, NULL, nrow = 1), 
          ncol = 1, rel_heights = c(1, 0.13), align = "vh")

```
